# Generated by Django 3.2 on 2022-09-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11, unique=True, verbose_name='账号')),
                ('upw', models.CharField(max_length=64, verbose_name='密码')),
                ('nickname', models.CharField(default='', max_length=8, verbose_name='昵称')),
            ],
        ),
    ]
