# Generated by Django 3.2 on 2022-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_webmasterstatistical'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='head_portrait',
            field=models.FileField(default='', null=True, upload_to='acc_head_portrait', verbose_name='头像'),
        ),
    ]
